import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const julesFont = localFont({
  src: "./../assets/fonts/julesbiglight-webfont.woff2",
  variable: "--font-julesbiglight",
});

const sebastianBobby = localFont({
  src: "./../assets/fonts/SebastianBobby.woff2",
  variable: "--font-sebastianBobby",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${julesFont.className} ${julesFont.variable} ${sebastianBobby.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
